colors:
  bright:
    black: '#434c5e'
    blue: '#81a1c1'
    cyan: '#88c0d0'
    green: '#a3be8c'
    magenta: '#b48ead'
    red: '#bf616a'
    white: '#e5e9f0'
    yellow: '#ebcb8b'
  normal:
    black: '#3b4252'
    blue: '#81a1c1'
    cyan: '#88c0d0'
    green: '#a3be8c'
    magenta: '#b48ead'
    red: '#bf616a'
    white: '#bfd5de'
    yellow: '#ebcb8b'
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
font:
  normal:
    family: SpaceMono Nerd Font
    style: Bold
  size: 12.0
window:
  opacity: 0.5
  padding:
    x: 3
    y: 3
shell:
  program: /bin/zsh
  args:
    - --login
